### ISSUE TITLE
Java8 Stream Api 적용 후 코드

### ISSUE THREAD

**Issue by pkgonan** [iamkyu/TIL#6]
적용 전에는 상위 3개에 대한 서브리스트를 추출하는 요구사항이
존재하는데

Java8 Stream Api 적용후 코드에는 해당 부분이 빠진 것 같아요.

**Comment by iamkyu** [comment]
https://github.com/iamkyu/TIL/blob/master/java/java-8-stream.md

위 문서의 예제 코드를 말씀하시는게 맞으신가요?
알려주셔서 감사합니다. 수정했습니다.
